version: '3'

services:

  traefik:
    image: traefik:v2.5
    command:
      # - "--log.level=DEBUG"
      # - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"

      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"

      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/.letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      # - "8080:8080"
    volumes:
      - "./.letsencrypt:/.letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik_network

  mailhog:
    image: mailhog/mailhog
#    labels:
#      - "traefik.enable=true"
#      - "traefik.docker.network=traefik_network"
#
#      - "traefik.http.routers.mailhog.entrypoints=http"
#      - "traefik.http.routers.mailhog.rule=Host(`mailhog.demo.kaizn.io`)"
#      - "traefik.http.routers.mailhog.middlewares=mailhog@docker"
#      - "traefik.http.middlewares.mailhog.redirectscheme.scheme=https"
#
#      - "traefik.http.routers.mailhog_https.entrypoints=https"
#      - "traefik.http.routers.mailhog_https.rule=Host(`mailhog.demo.kaizn.io`)"
#      - "traefik.http.routers.mailhog_https.tls.certresolver=letsencrypt"
#
#      - "traefik.http.services.mailhog.loadbalancer.server.port=8025"
    networks:
      - internal_network
#      - traefik_network
#    depends_on:
#      - traefik

  db:
    image: postgres:13.1-alpine
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DB_USERNAME}", "-d", "${DB_NAME}" ]
      interval: 15s
      timeout: 3s
      retries: 8
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - internal_network

  voy:
    image: project-p/voy
    build:
      context: .
    environment:
      - DB_HOST
      - DB_PORT
      - DB_NAME
      - DB_USERNAME
      - DB_PASSWORD
      - MAIL_HOST
      - MAIL_PORT
      - MAIL_USE_TLS
      - MAIL_USE_SSL
      - MAIL_DEBUG
      - MAIL_USERNAME
      - MAIL_PASSWORD
      - SECRET_KEY
      - FLASK_APP
      - FLASK_ENV
      - DEBUG
      - TESTING
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_network"

      - "traefik.http.routers.voy.entrypoints=http"
      - "traefik.http.routers.voy.rule=Host(`${VOY_HOST}`)"
      - "traefik.http.routers.voy.middlewares=voy@docker"
      - "traefik.http.middlewares.voy.redirectscheme.scheme=https"

      - "traefik.http.routers.voy_https.entrypoints=https"
      - "traefik.http.routers.voy_https.rule=Host(`${VOY_HOST}`)"
      - "traefik.http.routers.voy_https.tls.certresolver=letsencrypt"

      - "traefik.http.services.voy.loadbalancer.server.port=5000"
    networks:
      - internal_network
      - traefik_network
    depends_on:
      - db
      - mailhog
      - traefik

volumes:
  db:

networks:
  traefik_network:
    # Need to explicitly set the name, so that docker-compose does not prefix it.
    name: traefik_network
  internal_network:
