version: '3'

services:

  traefik:
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"

      - "--entrypoints.http.address=:${VOY_HTTP_PORT}"
      - "--entrypoints.https.address=:${VOY_HTTPS_PORT}"

      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/.letsencrypt/acme.json"
    ports:
      - "${VOY_HTTP_PORT}:80"
      - "${VOY_HTTPS_PORT}:443"
    volumes:
      - "${LETSENCRYPT_DATA_PATH}:/.letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  voy:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_network"

      - "traefik.http.routers.voy.entrypoints=http"
      - "traefik.http.routers.voy.rule=Host(`${VOY_HOST}`)"
      - "traefik.http.routers.voy.middlewares=voy@docker"
      - "traefik.http.middlewares.voy.redirectscheme.scheme=https"

      - "traefik.http.routers.voy_https.entrypoints=https"
      - "traefik.http.routers.voy_https.rule=Host(`${VOY_HOST}`)"
      - "traefik.http.routers.voy_https.tls.certresolver=letsencrypt"

      - "traefik.http.services.voy.loadbalancer.server.port=5000"
