version: 1

disable_existing_loggers: False

formatters:
  standard:  
    format: '%(asctime)s %(name)s %(levelname)s %(message)s'
  brief:
    format: '%(message)s'
  default:
    format: '%(asctime)s %(levelname)-8s [%(name)s] %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    formatter: default
    level: INFO
  file:
    class : logging.handlers.RotatingFileHandler
    formatter: default 
    level: INFO
    filename: server/.log_files/qc.log
    maxBytes: 1024
    backupCount: 3


