version: 1

disable_existing_loggers: True

# the desired logging formats 
# specify the design here and 
# call it in the 'handlers' over 'formatter:'
formatters:
  brief:
    format: '%(message)s'
  cro_qc:
    format: '%(asctime)s %(levelname)-8s [%(name)s] %(message)s'
    datefmt: '%d-%b-%Y %H:%M:%S'


handlers:
  console:
    class: logging.StreamHandler
    formatter: brief
    level: INFO
    stream: ext://sys.stdout
  qc_log:
    class : logging.handlers.RotatingFileHandler
    formatter: cro_qc 
    level: DEBUG
    filename: server/.log_files/qc.log
    maxBytes: 1024
    backupCount: 3

root:
  handlers: [console, qc_log]
  level: WARN

loggers:
  app:
    level: DEBUG
