ROLE_ADMIN = 'Admin'
ROLE_MEDOPS = 'MedOps'
ROLE_DATA_ENTRY = "Data Entry"
ROLE_DATA_MANAGER = "Data Manager"

EXPORT_FOLDER = 'data-exports'
FILE_TYPE_PDF  = 'pdf'
FILE_TYPE_XLSX = 'xlsx'

SOURCE_TYPE_SOURCE = "Source"
SOURCE_TYPE_ICF = "ICF"
AVAILABLE_SOURCE_TYPES = [SOURCE_TYPE_SOURCE, SOURCE_TYPE_ICF]

FLASH_TYPE_ERROR = 'error'
FLASH_TYPE_WARNING = 'warning'
FLASH_TYPE_SUCCESS = 'success'
