"""updated the model schemata for a better code validation and error handling

Revision ID: b000b8c44a16
Revises: 09cf4fd7fe4c
Create Date: 2021-03-03 07:15:15.950909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b000b8c44a16'
down_revision = '09cf4fd7fe4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('db_user', 'active', nullable=True, new_column_name='is_active')
    op.alter_column('qc_check', 'close',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               postgresql_using='close::boolean')
    op.alter_column('qc_check', 'corrected',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               postgresql_using='corrected::boolean')
    op.alter_column('qc_check', 'prioritized',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               postgresql_using='prioritized::boolean')
    op.alter_column('qc_check', 'study_id',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True,
               postgresql_using='study_id::text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('qc_check', 'study_id',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               postgresql_using='study_id::integer')
    op.alter_column('qc_check', 'prioritized',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               postgresql_using='prioritized::integer')
    op.alter_column('qc_check', 'corrected',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               postgresql_using='corrected::integer')
    op.alter_column('qc_check', 'close',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               postgresql_using='close::integer')
    op.alter_column('db_user', 'is_active', nullable=True, new_column_name='active')
    # ### end Alembic commands ###

